openapi: 3.0.3
info:
  version: 1.0.0
  title: api
  description: ""
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: テスト
    description: "テスト"
servers:
  - url: /

paths:
  /api/v1/clients:
    get:
      tags:
        - テスト
      summary: クライアント一覧取得
      operationId: test
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Client"
        "400":
          description: Bad Request

security:
  - JWT: []

components:
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Client:
      type: object
      properties:
        id:
          type: integer
          description: ID
        name:
          type: string
          description: 名前
          enum:
            - "テスト"
            - "テスト2"
        email:
          type: string
          description: メールアドレス
        createdAt:
          type: string
          description: 作成日時
        updatedAt:
          type: string
          description: 更新日時
