/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** クライアント一覧取得 */
        get: operations["\u30AF\u30E9\u30A4\u30A2\u30F3\u30C8\u4E00\u89A7\u53D6\u5F97"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Client: {
            /** @description ID */
            id?: number;
            /** @description 名前 */
            name?: string;
            /** @description メールアドレス */
            email?: string;
            /** @description 作成日時 */
            createdAt?: string;
            /** @description 更新日時 */
            updatedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "\u30AF\u30E9\u30A4\u30A2\u30F3\u30C8\u4E00\u89A7\u53D6\u5F97": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"];
                };
            };
        };
    };
}
